"""new fields in user model

Revision ID: 047ae5d041cb
Revises: bd5a2d8b3a54
Create Date: 2018-10-23 18:30:35.986735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047ae5d041cb'
down_revision = 'bd5a2d8b3a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
