"""fishery table

Revision ID: 12be0dee14b4
Revises: 1f0f1d09f00d
Create Date: 2018-11-10 20:53:20.945652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12be0dee14b4'
down_revision = '1f0f1d09f00d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fishery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservoir_name', sa.String(length=40), nullable=True),
    sa.Column('country', sa.String(length=40), nullable=True),
    sa.Column('place', sa.String(length=140), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fishery_country'), 'fishery', ['country'], unique=False)
    op.create_index(op.f('ix_fishery_reservoir_name'), 'fishery', ['reservoir_name'], unique=False)
    op.create_table('users_fisheries',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fishery_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fishery_id'], ['fishery.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_fisheries')
    op.drop_index(op.f('ix_fishery_reservoir_name'), table_name='fishery')
    op.drop_index(op.f('ix_fishery_country'), table_name='fishery')
    op.drop_table('fishery')
    # ### end Alembic commands ###
