"""Fishery table mod

Revision ID: 86db6ce9f3d4
Revises: 12be0dee14b4
Create Date: 2018-11-12 17:43:26.380679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86db6ce9f3d4'
down_revision = '12be0dee14b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fishery', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('fishery', sa.Column('modified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fishery', 'modified_at')
    op.drop_column('fishery', 'created_at')
    # ### end Alembic commands ###
